pipeline:
  name: infratestinlineenv
  identifier: infratestinlineenv
  projectIdentifier: Project1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: s1
          environment:
            environmentRef: testEnv
            environmentInputs:
              identifier: testEnv
              type: Production
              overrides:
                manifests:
                  - manifest:
                      identifier: aa
                      type: Values
                      spec:
                        store:
                          type: Github
                          spec:
                            connectorRef: <+input>
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infraforunlineenv
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  when:
                    stageStatus: Success
                    condition: 1==2
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
